/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyCongTyBongDa;

import java.awt.Color;
import java.util.*;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS TUF GAMING
 */
public class Gui extends javax.swing.JFrame {
    DefaultTableModel dtm;
    /**
     * Creates new form Gui
     */
    DanhSachNhanVien a = new DanhSachNhanVien();
    public Gui() {
        initComponents();
        setLocationRelativeTo(null);
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"Mã","Họ tên","Quốcc tịch","Vị trí","CLB","Nơi thi đấu",
            "Ngày sinh","Giới tính","Lương cố định","Số bàn thắng","Số kiến tạo","Số cứu thua","Năm kinh nghiệm","Trình độ","Phong cách","Lương"});
        tblHienThi.setModel(dtm);
        tblHienThi.setRowHeight(24);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField9 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblMa = new javax.swing.JLabel();
        lblHoVaTen = new javax.swing.JLabel();
        rbtCauThu = new javax.swing.JRadioButton();
        rbtHuanLuyenVien = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtNam = new javax.swing.JRadioButton();
        txtMa = new javax.swing.JTextField();
        txtHoVaTen = new javax.swing.JTextField();
        lblQuocTich = new javax.swing.JLabel();
        lblViTri = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();
        txtNgaySinh = new javax.swing.JTextField();
        txtQuocTich = new javax.swing.JTextField();
        txtViTri = new javax.swing.JTextField();
        lblCauLacBo = new javax.swing.JLabel();
        lblNoiThiDau = new javax.swing.JLabel();
        lblLuongCoDinh = new javax.swing.JLabel();
        txtLuongCoDinh = new javax.swing.JTextField();
        txtCauLacBo = new javax.swing.JTextField();
        lblChung1 = new javax.swing.JLabel();
        lblChung3 = new javax.swing.JLabel();
        lblChung2 = new javax.swing.JLabel();
        txtChung1 = new javax.swing.JTextField();
        txtChung2 = new javax.swing.JTextField();
        txtChung3 = new javax.swing.JTextField();
        cbxNoiThiDau = new javax.swing.JComboBox<>();
        lblGioiTinh = new javax.swing.JLabel();
        btnDocFile = new javax.swing.JButton();
        btnGhiFile = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnSuaThongTin = new javax.swing.JButton();
        btnLuongCaoNhat = new javax.swing.JButton();
        btnCuuThuaCaoNhat = new javax.swing.JButton();
        btnGiamTheoLuong = new javax.swing.JButton();
        btnInDanhSach = new javax.swing.JButton();
        btnHLVItKinhNghiemNhat = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnTongBanThang = new javax.swing.JButton();
        rbtNu = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblStatus = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cong ty bong da");
        setResizable(false);

        lblMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMa.setForeground(new java.awt.Color(51, 51, 51));
        lblMa.setText("Mã");

        lblHoVaTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHoVaTen.setForeground(new java.awt.Color(51, 51, 51));
        lblHoVaTen.setText("Họ và Tên");

        rbtCauThu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtCauThu);
        rbtCauThu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtCauThu.setForeground(new java.awt.Color(51, 51, 51));
        rbtCauThu.setSelected(true);
        rbtCauThu.setText("Cầu thủ");
        rbtCauThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCauThuActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtHuanLuyenVien);
        rbtHuanLuyenVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtHuanLuyenVien.setForeground(new java.awt.Color(51, 51, 51));
        rbtHuanLuyenVien.setText("Huấn luyện viên");
        rbtHuanLuyenVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHuanLuyenVienActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 37)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("QUẢN LÝ CÔNG TY BÓNG ĐÁ");

        buttonGroup2.add(rbtNam);
        rbtNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtNam.setForeground(new java.awt.Color(51, 51, 51));
        rbtNam.setText("Nam");

        txtMa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMa.setForeground(new java.awt.Color(51, 51, 51));
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        txtHoVaTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHoVaTen.setForeground(new java.awt.Color(51, 51, 51));
        txtHoVaTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoVaTenActionPerformed(evt);
            }
        });

        lblQuocTich.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuocTich.setForeground(new java.awt.Color(51, 51, 51));
        lblQuocTich.setText("Quốc tịch");

        lblViTri.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblViTri.setForeground(new java.awt.Color(51, 51, 51));
        lblViTri.setText("Vị trí");

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgaySinh.setForeground(new java.awt.Color(51, 51, 51));
        lblNgaySinh.setText("Ngày sinh");

        tblHienThi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHienThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHienThi);

        txtNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNgaySinh.setForeground(new java.awt.Color(51, 51, 51));
        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        txtQuocTich.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuocTich.setForeground(new java.awt.Color(51, 51, 51));
        txtQuocTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuocTichActionPerformed(evt);
            }
        });

        txtViTri.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtViTri.setForeground(new java.awt.Color(51, 51, 51));
        txtViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViTriActionPerformed(evt);
            }
        });

        lblCauLacBo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCauLacBo.setForeground(new java.awt.Color(51, 51, 51));
        lblCauLacBo.setText("CLB");

        lblNoiThiDau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNoiThiDau.setForeground(new java.awt.Color(51, 51, 51));
        lblNoiThiDau.setText("Nơi thi đấu");

        lblLuongCoDinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLuongCoDinh.setForeground(new java.awt.Color(51, 51, 51));
        lblLuongCoDinh.setText("Lương cố định");

        txtLuongCoDinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLuongCoDinh.setForeground(new java.awt.Color(51, 51, 51));
        txtLuongCoDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongCoDinhActionPerformed(evt);
            }
        });

        txtCauLacBo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCauLacBo.setForeground(new java.awt.Color(51, 51, 51));
        txtCauLacBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCauLacBoActionPerformed(evt);
            }
        });

        lblChung1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChung1.setForeground(new java.awt.Color(51, 51, 51));
        lblChung1.setText("Số bàn thắng");

        lblChung3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChung3.setForeground(new java.awt.Color(51, 51, 51));
        lblChung3.setText("Số cứu thua");

        lblChung2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChung2.setForeground(new java.awt.Color(51, 51, 51));
        lblChung2.setText("Số kiến tạo");

        txtChung1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtChung1.setForeground(new java.awt.Color(51, 51, 51));

        txtChung2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtChung2.setForeground(new java.awt.Color(51, 51, 51));
        txtChung2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChung2ActionPerformed(evt);
            }
        });

        txtChung3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtChung3.setForeground(new java.awt.Color(51, 51, 51));
        txtChung3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChung3ActionPerformed(evt);
            }
        });

        cbxNoiThiDau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxNoiThiDau.setForeground(new java.awt.Color(51, 51, 51));
        cbxNoiThiDau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TN", "NN" }));
        cbxNoiThiDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNoiThiDauActionPerformed(evt);
            }
        });

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(51, 51, 51));
        lblGioiTinh.setText("Giới tính");

        btnDocFile.setBackground(new java.awt.Color(0, 204, 255));
        btnDocFile.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnDocFile.setText("Đọc file");
        btnDocFile.setToolTipText("");
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        btnGhiFile.setBackground(new java.awt.Color(0, 204, 255));
        btnGhiFile.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnGhiFile.setText("Ghi file");
        btnGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiFileActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(0, 204, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(0, 204, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(0, 204, 255));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnSuaThongTin.setBackground(new java.awt.Color(0, 204, 255));
        btnSuaThongTin.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnSuaThongTin.setText("Sửa thông tin");
        btnSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinActionPerformed(evt);
            }
        });

        btnLuongCaoNhat.setBackground(new java.awt.Color(0, 204, 255));
        btnLuongCaoNhat.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnLuongCaoNhat.setText("Lương cao nhất");
        btnLuongCaoNhat.setActionCommand("");
        btnLuongCaoNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongCaoNhatActionPerformed(evt);
            }
        });

        btnCuuThuaCaoNhat.setBackground(new java.awt.Color(0, 204, 255));
        btnCuuThuaCaoNhat.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnCuuThuaCaoNhat.setText("Cứu thua cao nhất");
        btnCuuThuaCaoNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuuThuaCaoNhatActionPerformed(evt);
            }
        });

        btnGiamTheoLuong.setBackground(new java.awt.Color(0, 204, 255));
        btnGiamTheoLuong.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnGiamTheoLuong.setText("Giảm theo lương");
        btnGiamTheoLuong.setToolTipText("");
        btnGiamTheoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamTheoLuongActionPerformed(evt);
            }
        });

        btnInDanhSach.setBackground(new java.awt.Color(0, 204, 255));
        btnInDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnInDanhSach.setText("In danh sách");
        btnInDanhSach.setToolTipText("");
        btnInDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInDanhSachActionPerformed(evt);
            }
        });

        btnHLVItKinhNghiemNhat.setBackground(new java.awt.Color(0, 204, 255));
        btnHLVItKinhNghiemNhat.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnHLVItKinhNghiemNhat.setText("HLV ít kinh nghiệm nhất");
        btnHLVItKinhNghiemNhat.setToolTipText("");
        btnHLVItKinhNghiemNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHLVItKinhNghiemNhatActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 0, 0));
        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButton12.setText("Thoát");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btnTongBanThang.setBackground(new java.awt.Color(0, 204, 255));
        btnTongBanThang.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnTongBanThang.setText("Tổng bàn thắng");
        btnTongBanThang.setActionCommand("");
        btnTongBanThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongBanThangActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtNu);
        rbtNu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtNu.setForeground(new java.awt.Color(51, 51, 51));
        rbtNu.setText("Nữ");
        rbtNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNuActionPerformed(evt);
            }
        });

        lblStatus.setText("Trạng thái");

        btnReset.setBackground(new java.awt.Color(255, 0, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(36, 36, 36))
                            .addComponent(lblHoVaTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(rbtNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtNu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtCauThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(60, 60, 60))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHoVaTen, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtMa, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblQuocTich, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCauLacBo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuocTich)
                                    .addComponent(txtCauLacBo)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(80, 80, 80))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtHuanLuyenVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(244, 244, 244)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLuongCoDinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNoiThiDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblViTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxNoiThiDau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(83, 83, 83))
                            .addComponent(txtLuongCoDinh)
                            .addComponent(txtViTri))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblChung1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtChung1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblChung3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblChung2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChung3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtChung2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGhiFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDocFile, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCuuThuaCaoNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGiamTheoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHLVItKinhNghiemNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(btnSuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLuongCaoNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTongBanThang, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtCauThu)
                            .addComponent(rbtHuanLuyenVien)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton12)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLuongCoDinh)
                    .addComponent(txtLuongCoDinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChung1)
                    .addComponent(lblNgaySinh)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChung1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoVaTen)
                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChung2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChung2)
                    .addComponent(lblNoiThiDau)
                    .addComponent(cbxNoiThiDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuocTich)
                    .addComponent(txtQuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtNam)
                    .addComponent(lblCauLacBo)
                    .addComponent(txtCauLacBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChung3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChung3)
                    .addComponent(txtViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViTri)
                    .addComponent(lblGioiTinh)
                    .addComponent(rbtNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocFile)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnTimKiem)
                    .addComponent(btnSuaThongTin)
                    .addComponent(btnLuongCaoNhat))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHLVItKinhNghiemNhat)
                    .addComponent(btnTongBanThang)
                    .addComponent(btnInDanhSach)
                    .addComponent(btnGiamTheoLuong)
                    .addComponent(btnCuuThuaCaoNhat)
                    .addComponent(btnGhiFile))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtHuanLuyenVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHuanLuyenVienActionPerformed
        lblChung1.setText("Số năm kinh nghiệm");
        lblChung2.setText("Phong cách");
        lblChung3.setText("Trình độ");
    }//GEN-LAST:event_rbtHuanLuyenVienActionPerformed

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void txtHoVaTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoVaTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoVaTenActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtQuocTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuocTichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuocTichActionPerformed

    private void txtViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViTriActionPerformed

    private void txtLuongCoDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongCoDinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongCoDinhActionPerformed

    private void txtCauLacBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCauLacBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCauLacBoActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void txtChung2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChung2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChung2ActionPerformed

    private void txtChung3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChung3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChung3ActionPerformed

    private void cbxNoiThiDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNoiThiDauActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cbxNoiThiDauActionPerformed

    private void rbtCauThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCauThuActionPerformed
            // TODO add your handling code here:
            lblChung1.setText("Số bàn thắng");
            lblChung2.setText("Số kiến tạo");
            lblChung3.setText("Số cứu thua");
    }//GEN-LAST:event_rbtCauThuActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        String tenFile = fc.getSelectedFile().getPath();       
        a.docFile(tenFile);
        loadData(a.getA());
        successfully("Đọc file thành công");
        
    }//GEN-LAST:event_btnDocFileActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtMa.getText().isEmpty() || txtHoVaTen.getText().isEmpty() || txtQuocTich.getText().isEmpty() ||
                txtViTri.getText().isEmpty() ||  txtCauLacBo.getText().isEmpty() || txtNgaySinh.getText().isEmpty()|| 
                txtLuongCoDinh.getText().isEmpty() || txtChung1.getText().isEmpty() || txtChung1.getText().isEmpty() || txtChung3.getText().isEmpty() ) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin");
        return; 
    }
        String ma = txtMa.getText();
        String hoTen = txtHoVaTen.getText();
        String quocTich = txtQuocTich.getText();
        String vt = txtViTri.getText();
        String cauLacBo = txtCauLacBo.getText();
        String noiCongTac = (String) cbxNoiThiDau.getSelectedItem();
        Date ngaySinh = new Date(txtNgaySinh.getText());
        boolean gt = rbtNam.isSelected();
        double luongCoDinh = Double.parseDouble(txtLuongCoDinh.getText());
        NhanVien x;
        if(rbtCauThu.isSelected()){
            int soBanThang = Integer.parseInt(txtChung1.getText());
            int soKienTao = Integer.parseInt(txtChung2.getText());
            int soCuuThua = Integer.parseInt(txtChung3.getText());
            x = new CauThu(soBanThang, soKienTao, soCuuThua, ma, hoTen, quocTich, vt, cauLacBo, noiCongTac, ngaySinh, gt, luongCoDinh);
        }
        else{
            int soNamKinhNghiem = Integer.parseInt(txtChung1.getText());
            String trinhDo = txtChung2.getText();
            String phongCach = txtChung3.getText();
            x =  new HuanLuyenVien(soNamKinhNghiem, trinhDo, phongCach, ma, hoTen, quocTich, vt, cauLacBo, noiCongTac, ngaySinh, gt, luongCoDinh);
                }
        int chon = JOptionPane.showConfirmDialog(null, "Bạn muốn thêm thông tin");
        if(chon==0){
            if(a.themNhanVien(x)){
                loadData(a.getA());
                successfully("Đã thêm thành công");
            }
            else   { 
                JOptionPane.showMessageDialog(null,"Mã đã tồn tại trong danh sách");  
                error("Đã thêm thất bại");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTongBanThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongBanThangActionPerformed
        // TODO add your handling code here:
         if(rbtCauThu.isSelected()){
            int banThang= a.tongSoBanThang();
            JOptionPane.showMessageDialog(null, "Tổng bàn thắng đạt được: "+banThang);
        }
         else if(rbtHuanLuyenVien.isSelected()){
            JOptionPane.showMessageDialog(null, "Không thể thống kê bàn thắng. Vui lòng chọn cầu thủ");
    }
        
    }//GEN-LAST:event_btnTongBanThangActionPerformed

    private void rbtNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNuActionPerformed
    public void capNhatBang(ArrayList<NhanVien> max){
        dtm.setRowCount(0);       
        if(max!=null){
            loadData(max);
        }
    }
    private void btnLuongCaoNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongCaoNhatActionPerformed
        // TODO add your handling code here:
        ArrayList<NhanVien> b= a.maxLuong();
        capNhatBang(b);  
        if(dtm.getRowCount()==1){
            int rowPoint = a.maxL();
            NhanVien sp = a.getPostion(rowPoint);
            setModal(sp);             
        }    
        successfully("Hiển thị cầu thủ/huấn luyện viên có lương cao nhất thành công");
    }//GEN-LAST:event_btnLuongCaoNhatActionPerformed

    private void btnCuuThuaCaoNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuuThuaCaoNhatActionPerformed
        // TODO add your handling code here:
        ArrayList<NhanVien> b= a.maxSoCuuThua();
        capNhatBang(b);
        if(dtm.getRowCount()==1){
            int rowPoint = a.maxC();
            NhanVien sp = a.getPostion(rowPoint);
            setModal(sp);      
            successfully("Hiển thị cầu thủ có số cứu thua cao nhất thành công");
        }
         else{
            error("Hiển thị cầu thủ có số cứu thua cao nhất thất bại");
        }
    }//GEN-LAST:event_btnCuuThuaCaoNhatActionPerformed

    private void btnSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(null, "Bạn muốn sửa thông tin");
        if(chon==0){
            int i= tblHienThi.getSelectedRow();
            String ma = txtMa.getText();
            String hoTen = txtHoVaTen.getText();
            String quocTich = txtQuocTich.getText();
            String viTri = txtViTri.getText();
            String clb =txtCauLacBo.getText();
            String noiThiDau = (String )cbxNoiThiDau.getSelectedItem();
            Date ngaySinh = new Date(txtNgaySinh.getText());
            boolean gt =rbtNam.isSelected();  
            double luongCoDinh = Double.parseDouble(txtLuongCoDinh.getText());
            NhanVien x;
            if(rbtCauThu.isSelected()){
                int soBanThang = Integer.parseInt(txtChung1.getText());
                int soKienTao = Integer.parseInt(txtChung2.getText());
                int soCuuThua = Integer.parseInt(txtChung3.getText());
                x = new CauThu(soBanThang, soKienTao, soCuuThua, ma, hoTen, quocTich, viTri, clb, noiThiDau, ngaySinh, gt, luongCoDinh);
            }
            else{
                int soNamKinhNghiem = Integer.parseInt(txtChung1.getText());
                String trinhDo = txtChung2.getText();
                String phongCach = txtChung3.getText();
                x = new HuanLuyenVien(soNamKinhNghiem, trinhDo, phongCach, ma, hoTen, quocTich, viTri, clb, noiThiDau, ngaySinh, gt, luongCoDinh);
                    }
            ArrayList<NhanVien> b =a.getA();
            if (i >= 0 && i < b.size()) {
                b.set(i, x);
                a.setA(b);
                loadData(a.getA());
                successfully("Sửa thành công");
        }          
        }
          else {
            JOptionPane.showMessageDialog(null, "Thông tin không hợp lệ trong danh sách.");
            error("Sửa thất bại");
        }
                  
    }//GEN-LAST:event_btnSuaThongTinActionPerformed

    private void tblHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHienThiMouseClicked
        // TODO add your handling code here:
        int i = tblHienThi.getSelectedRow();
        ArrayList<NhanVien> b = a.getA();
        NhanVien y = b.get(i);             
            if(y instanceof CauThu){
                rbtCauThu.setSelected(true);
                lblChung1.setText("Số bàn thắng");
                lblChung2.setText("Phong kiến tạo");
                lblChung3.setText("Số cứu thua");
                txtChung1.setText(""+((CauThu) y).getSoBanThang());
                txtChung2.setText(""+((CauThu) y).getSoKienTao());
                txtChung3.setText(""+((CauThu) y).getSoCuuThua());
        }
            else{
                rbtHuanLuyenVien.setSelected(true);
                lblChung1.setText("Số năm kinh nghiệm");
                lblChung2.setText("Phong cách");
                lblChung3.setText("Trình độ");
                txtChung1.setText(""+((HuanLuyenVien)y).getSoNamKinhNghiem());
                txtChung2.setText(""+((HuanLuyenVien)y).getPhongCach());
                txtChung3.setText(""+((HuanLuyenVien)y).getTrinhDo());
            }
            txtMa.setText(y.getMa());
            txtHoVaTen.setText(y.getHoTen());
            if(y.isGioiTinh()) {
                rbtNam.setSelected(true);
            }
            else {
                rbtNu.setSelected(true);
            }
            txtNgaySinh.setText(""+y.getNgaySinh());
            txtQuocTich.setText(y.getQuocTich());
            txtCauLacBo.setText(y.getCauLacBo());
            cbxNoiThiDau.setSelectedItem(y.getNoiCongTac());
            txtViTri.setText(y.getViTri());
            txtLuongCoDinh.setText(""+y.getLuongCoDinh());
        
     
    }//GEN-LAST:event_tblHienThiMouseClicked
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String ma = JOptionPane.showInputDialog(null,"Nhập mã cần xóa");
        boolean daXoa = a.xoaTheoMa(ma);
        int chon = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa thông tin "+ ma);
        if(chon==0){
            if (daXoa) {
                loadData(a.getA());
                successfully("Đã xóa thành công");
            }
           else {
                JOptionPane.showMessageDialog(null, "Không tìm thấy mã cần xóa.");
                error("Đã xóa thất bại");
            }     
       }      
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnHLVItKinhNghiemNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHLVItKinhNghiemNhatActionPerformed
        // TODO add your handling code here:
        ArrayList<NhanVien> b = a.huanLuyenVienItKinhNghiemNhat();
        capNhatBang(b);
        if(dtm.getRowCount()==1){
            int rowPoint = a.min();
            NhanVien sp = a.getPostion(rowPoint);
            setModal(sp);
            successfully("Hiển thị HLV ít kinh nghiệm nhất thành công");
        }
        else{
            error("Hiển thị HLV ít kinh nghiệm nhất thất bại");
        }
    }//GEN-LAST:event_btnHLVItKinhNghiemNhatActionPerformed

    private void btnGiamTheoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamTheoLuongActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        loadData(a.sapXepGiamTheoLuong());
        successfully("Sắp xếp giảm dần theo lương thành công");
    }//GEN-LAST:event_btnGiamTheoLuongActionPerformed

    private void btnInDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInDanhSachActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        if(rbtCauThu.isSelected()){
            ArrayList<NhanVien> danhSachCauThu = a.inDanhSachCauThuHuanLuyenVien("CauThu");
            loadData(danhSachCauThu); 
            successfully("Hiển thị danh sách cầu thủ thành công");
        }
        else if(rbtHuanLuyenVien.isSelected()){
            ArrayList<NhanVien> danhSachHuanLuyenVien = a.inDanhSachCauThuHuanLuyenVien("HuanLuyenVien");
            loadData(danhSachHuanLuyenVien);
            successfully("Hiển thị danh sách huấn luyện viên thành công");
        }
    }//GEN-LAST:event_btnInDanhSachActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maTimKiem = JOptionPane.showInputDialog(null, "Nhập mã cần tìm kiếm");
        NhanVien timKiem = a.timKiemTheoMa(maTimKiem);
        int chon = JOptionPane.showConfirmDialog(null, "Bạn muốn tìm kiếm thông tin "+maTimKiem);
        if(chon==0){
            if (timKiem!=null) {
                ArrayList<NhanVien> ketQua = new ArrayList<>();
                ketQua.add(timKiem);
                loadData(ketQua);
                setModal(timKiem);
                successfully("Tìm kiếm thành công");
            }
           else {
                JOptionPane.showMessageDialog(null, "Không tìm thấy mã cần tìm.");
                error("Tìm kiếm thất bại");
            }     
       }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    public void setModal(NhanVien x){
        txtMa.setText(x.getMa());
        txtCauLacBo.setText(x.getCauLacBo());
        txtHoVaTen.setText(x.getHoTen());
        txtQuocTich.setText(x.getQuocTich());
        Date ngaySinh = x.getNgaySinh();
        txtNgaySinh.setText(ngaySinh.toString());
        txtLuongCoDinh.setText(""+x.getLuongCoDinh());
         int i = tblHienThi.getSelectedRow();        
        if(x.isGioiTinh()) {
                rbtNam.setSelected(true);
            }
            else {
                rbtNu.setSelected(true);
            }
        cbxNoiThiDau.setSelectedItem(x.getNoiCongTac());
        txtViTri.setText(x.getViTri());
        if(x instanceof CauThu){
                rbtCauThu.setSelected(true);
                txtChung1.setText(""+((CauThu) x).getSoBanThang());
                txtChung2.setText(""+((CauThu) x).getSoKienTao());
                txtChung3.setText(""+((CauThu) x).getSoCuuThua());
        }
        else if(x instanceof HuanLuyenVien){
                rbtHuanLuyenVien.setSelected(true);
                txtChung1.setText(""+((HuanLuyenVien)x).getSoNamKinhNghiem());
                txtChung2.setText(""+((HuanLuyenVien)x).getPhongCach());
                txtChung3.setText(""+((HuanLuyenVien)x).getTrinhDo());
            }       
    }   
    private void btnGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiFileActionPerformed
        // TODO add your handling code here:
        String tenFile = JOptionPane.showInputDialog(null, "Nhập file muốn lưu");
        int chon = JOptionPane.showConfirmDialog(null, "Bạn muốn lưu vào file " + tenFile);
        if(chon==0){
            a.ghiFile(tenFile);
            successfully("Ghi file thành công");
        }
        else{
            error("Ghi file thất bại. Vui lòng thử lại");
        }
    }//GEN-LAST:event_btnGhiFileActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
        loadData(a.getA());
        successfully("Đã reset");
    }//GEN-LAST:event_btnResetActionPerformed
    public void loadData(ArrayList<NhanVien> b){
        while(dtm.getRowCount()>0) dtm.removeRow(0);
        for(NhanVien x:b){
            if(x instanceof CauThu){
                dtm.addRow(new Object[]{x.getMa(),x.getHoTen(),x.getQuocTich(),x.getViTri(),x.getCauLacBo(),
                    x.getNoiCongTac(),x.getNgaySinh(),(x.isGioiTinh()== true?"Nam" :"Nu"),x.getLuongCoDinh(),((CauThu) x).getSoBanThang(),
                    ((CauThu) x).getSoKienTao(),((CauThu) x).getSoCuuThua(),"","","",x.getLuong()});
            }
            if(x instanceof HuanLuyenVien){
                dtm.addRow(new Object[]{x.getMa(),x.getHoTen(),x.getQuocTich(),x.getViTri(),x.getCauLacBo(),
                    x.getNoiCongTac(),x.getNgaySinh(),(x.isGioiTinh()== true?"Nam" :"Nu"),x.getLuongCoDinh(),"","","",((HuanLuyenVien) x).getSoNamKinhNghiem(),
                    ((HuanLuyenVien) x).getTrinhDo(),((HuanLuyenVien) x).getPhongCach(),x.getLuong()});
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public void successfully(String name){
        lblStatus.setText(name);
        lblStatus.setForeground(Color.blue);        
    }
    public void error(String name){
        lblStatus.setText("Cảnh báo: "+name);
        lblStatus.setForeground(Color.red);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuuThuaCaoNhat;
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnGhiFile;
    private javax.swing.JButton btnGiamTheoLuong;
    private javax.swing.JButton btnHLVItKinhNghiemNhat;
    private javax.swing.JButton btnInDanhSach;
    private javax.swing.JButton btnLuongCaoNhat;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSuaThongTin;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTongBanThang;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxNoiThiDau;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblCauLacBo;
    private javax.swing.JLabel lblChung1;
    private javax.swing.JLabel lblChung2;
    private javax.swing.JLabel lblChung3;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoVaTen;
    private javax.swing.JLabel lblLuongCoDinh;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNoiThiDau;
    private javax.swing.JLabel lblQuocTich;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblViTri;
    private javax.swing.JRadioButton rbtCauThu;
    private javax.swing.JRadioButton rbtHuanLuyenVien;
    private javax.swing.JRadioButton rbtNam;
    private javax.swing.JRadioButton rbtNu;
    private javax.swing.JTable tblHienThi;
    private javax.swing.JTextField txtCauLacBo;
    private javax.swing.JTextField txtChung1;
    private javax.swing.JTextField txtChung2;
    private javax.swing.JTextField txtChung3;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtLuongCoDinh;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
